[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 10
auto_detect_solc = false
solc_version = "0.8.18"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
libraries = ["src/libraries/logic/ETokenDeployer.sol:ETokenDeployer:0xecce0f5e758d01c142ebd5ed2565038e4c0edd80", "src/libraries/logic/ReserveLogic.sol:ReserveLogic:0xec120bc6e12cea127553b1f53445947b1f73a132", "src/libraries/logic/StakingRewardsDeployer.sol:StakingRewardsDeployer:0xcefa665165281b7a9807bdcd4d7ac54a54ca1e13"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
